apiVersion: v1
kind: Pod
metadata:
  name: test-signal-tracker
  namespace: production
  labels:
    app: signal-tracker
spec:
  restartPolicy: Never
  containers:
    - name: signal-tracker
      image: registry-docker-registry.registry.svc.cluster.local:5000/signal-tracker:latest
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "Starting app.py..." && \
          cd /app && ./python main.py || echo "main failed" && \
          echo "Sleeping for debug..." && sleep 3600
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
      envFrom:
        - secretRef:
            name: db-creds

        - secretRef:
            name: telegram
